plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'

    id 'io.github.ben-manes.versions.settings' version '0.61.0'

    // https://git.sr.ht/~ajoberstar/reckon
    id 'org.ajoberstar.reckon.settings' version '2.0.0'
}

reckon {
    defaultInferredScope = 'patch'
    stages 'dev', 'final'
    scopeCalc = calcScopeFromProp()
    stageCalc = calcStageFromProp()
}

import com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask

def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r|-jre|-android)?$/
    return !stableKeyword && !(version ==~ regex)
}
gradle.rootProject {
    tasks.withType(DependencyUpdatesTask).configureEach {
        checkConstraints = true

        rejectVersionIf {
            isNonStable(candidate.version)
        }
    }
}

rootProject.name = 'staff-duty'
include 'app'
project(":app").name = 'staff-duty'

